DATASET:
#  ROOT:  '/shared/tale2/Shared/data/EgoAction/'
  SOURCE: 'EPIC'
  SRC_TRAINLIST: 'epic_D1_train.pkl'
  SRC_TESTLIST: 'epic_D1_test.pkl'
  TARGET: 'EPIC'
  TGT_TRAINLIST: 'epic_D2_train.pkl'
  TGT_TESTLIST: 'epic_D2_test.pkl'
  IMAGE_MODALITY: 'rgb'
DAN:
  METHOD: 'DAN'
MODEL:
  METHOD: 'r3d_18'
OUTPUT:
  TB_DIR: 'lightning_logs/EPIC-d12d2-dan/'
