DAN:
  METHOD: "M3SDA"
DATASET:
  NAME: "office"
  NUM_CLASSES: 10
  ROOT: "../data/Office"
  TARGET: "amazon"
  SOURCE: ["dslr", "webcam"]
  NUM_REPEAT: 1
SOLVER:
  TRAIN_BATCH_SIZE: 100
  TEST_BATCH_SIZE: 100
OUTPUT:
  TB_DIR: "lightning_logs/office_caltech/M3SDA/Tgt_amazon"
