DAN:
  METHOD: "M3SDA"
DATASET:
  NAME: "office_caltech"
  NUM_CLASSES: 10
  ROOT: "../data/office"
  TARGET: "amazon"
  NUM_REPEAT: 5
SOLVER:
  TRAIN_BATCH_SIZE: 40
  TEST_BATCH_SIZE: 40
OUTPUT:
  OUT_DIR: "outputs/office_caltech/M3SDA/Tgt_amazon"
