# This workflow will automatically add an issue or pull request to the default project.
# The project needs to be updated when we move to a new default project.
# https://github.com/marketplace/actions/assign-to-one-project

name: assign project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to one default project
    steps:
    - name: Assign NEW issues and NEW pull requests to a default project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/pykale/pykale/projects/9'
